### ISSUE TITLE
Install-SdnDiagnostics failed to install module on remote machine

### ISSUE THREAD

**Issue by luyaof** [microsoft/SdnDiagnostics#91]
**Describe the bug**
The module installed to path like `C:\Program Files\WindowsPowerShell\Modules\1.2109.76.448\SdnDiagnostics.psm1` and failed to be auto loaded when run any command from the SdnDiagnostics module

**To Reproduce**
1. Install module from PS gallery on a jump box.
2. Run `Install-SdnDiagnostics` to install the module to remote infra nodes

**Expected behavior**
Expect to be able to run SdnDiagnostics cmdlet after module installed but not actually due to the incorrect module path copied.

**Screenshots**
Module on local machine:
![image](https://user-images.githubusercontent.com/50725564/141428212-ddfe2416-3e0d-4b15-b684-957d928d74f6.png)

Module on remote machine by Install-SdnDiagnostics
![image](https://user-images.githubusercontent.com/50725564/141428361-06f6abbc-24a8-465a-bf3d-ca1bf213f489.png)

**Environment Details (please complete the following information):**
 - Windows Server OS: Server 2019
 - SdnDiagnostics Version: 1.2109.76.448

**Comment by arudell** [comment]
@luyaof I think with where the project is at, we can look to retire `Install-SdnDiagnostics` and instead leverage `Install-Module` as the primary method for installation since it creates the SdnDiagnostics\x.xxxx.xx.xxx folders.

We then just need to create some internal functions to handle auto-updating and if nodes do not have internet access, then to manually seed the module out to the nodes in format that aligns with `Install-Module`

**Comment by luyaof** [comment]
The `Install-SdnDiagnostics` is needed as public function to support the environment with no Internet access. My proposal is to:
- `Install-Module` as the primary method for source computer that going to run `Install-SdnDiagnostics`. I am figuring out how to properly install module for test function during development.
- `Install-SdnDiagnostics` only support copy module from PSModule path with format aligns with the `Install-Module`
